# Generated by Django 5.1.2 on 2024-10-24 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('direccion_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_empresa', models.CharField(blank=True, max_length=10, null=True)),
                ('email_empresa', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Ocupaciones',
            fields=[
                ('id_ocupacion', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_ocupacion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ocupaciones',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('password_usuario', models.CharField(max_length=50)),
                ('fecha_caducidad', models.DateField()),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Egresados',
            fields=[
                ('id_egresado', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_egresado', models.CharField(max_length=30)),
                ('apellido_egresado', models.CharField(max_length=30)),
                ('direccion_egresado', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_egresado', models.CharField(blank=True, max_length=10, null=True)),
                ('email_egresado', models.CharField(blank=True, max_length=100, null=True)),
                ('estatus_egresado', models.CharField(blank=True, max_length=15, null=True)),
                ('id_ocupacion', models.ForeignKey(blank=True, db_column='id_ocupacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Solicitudes.ocupaciones')),
            ],
            options={
                'db_table': 'egresados',
            },
        ),
        migrations.CreateModel(
            name='SolicitudesServicio',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('perfil_solicitud', models.TextField(blank=True, null=True)),
                ('estatus_solicitud', models.SmallIntegerField(blank=True, null=True)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Solicitudes.empresas')),
                ('id_ocupacion', models.ForeignKey(blank=True, db_column='id_ocupacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Solicitudes.ocupaciones')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Solicitudes.usuarios')),
            ],
            options={
                'db_table': 'solicitudes_servicio',
            },
        ),
        migrations.CreateModel(
            name='DetallesSolicitud',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_detalle', models.SmallIntegerField(blank=True, null=True)),
                ('id_egresado', models.ForeignKey(blank=True, db_column='id_egresado', null=True, on_delete=django.db.models.deletion.CASCADE, to='Solicitudes.egresados')),
                ('id_solicitud', models.ForeignKey(blank=True, db_column='id_solicitud', null=True, on_delete=django.db.models.deletion.CASCADE, to='Solicitudes.solicitudesservicio')),
            ],
            options={
                'db_table': 'detalles_solicitud',
            },
        ),
    ]
