# Generated by Django 5.1.2 on 2024-10-24 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudesservicio',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='solicitudesservicio',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='egresados',
            name='email_egresado',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='egresados',
            name='telefono_egresado',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='email_empresa',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='telefono_empresa',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesservicio',
            name='estatus_solicitud',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Pendiente'), (2, 'En Proceso'), (3, 'Completado'), (4, 'Cancelado')], null=True),
        ),
        migrations.AlterModelTable(
            name='detallessolicitud',
            table=None,
        ),
        migrations.AlterModelTable(
            name='egresados',
            table=None,
        ),
        migrations.AlterModelTable(
            name='empresas',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ocupaciones',
            table=None,
        ),
        migrations.AlterModelTable(
            name='solicitudesservicio',
            table=None,
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
