# Generated by Django 5.1.2 on 2024-10-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0003_alter_egresados_estatus_egresado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallessolicitud',
            name='selected_egresado',
            field=models.BooleanField(default=False),
        ),
    ]
