# Generated by Django 5.1.2 on 2024-10-26 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0005_alter_detallessolicitud_estatus_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallessolicitud',
            name='estatus_detalle',
        ),
        migrations.AddField(
            model_name='detallessolicitud',
            name='estatus_solicitud',
            field=models.ForeignKey(blank=True, db_column='estatus_solicitud', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estatus_detalles', to='Solicitudes.solicitudesservicio'),
        ),
        migrations.AlterField(
            model_name='detallessolicitud',
            name='id_solicitud',
            field=models.ForeignKey(blank=True, db_column='id_solicitud', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_solicitud', to='Solicitudes.solicitudesservicio'),
        ),
        migrations.AlterField(
            model_name='solicitudesservicio',
            name='estatus_solicitud',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Pendiente'), (2, 'En Proceso'), (3, 'Completado')], null=True),
        ),
    ]
